package com.king.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-02-05T16:27:26.832+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "WeatherServiceImplService", 
                  wsdlLocation = "http://localhost:8077/7_ApacheCXF_Spring_integration/services/WeatherServiceImplPort?wsdl",
                  targetNamespace = "http://service.king.com/") 
public class WeatherServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.king.com/", "WeatherServiceImplService");
    public final static QName WeatherServiceImplPort = new QName("http://service.king.com/", "WeatherServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8077/7_ApacheCXF_Spring_integration/services/WeatherServiceImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8077/7_ApacheCXF_Spring_integration/services/WeatherServiceImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WeatherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WeatherServiceImpl
     */
    @WebEndpoint(name = "WeatherServiceImplPort")
    public WeatherServiceImpl getWeatherServiceImplPort() {
        return super.getPort(WeatherServiceImplPort, WeatherServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherServiceImpl
     */
    @WebEndpoint(name = "WeatherServiceImplPort")
    public WeatherServiceImpl getWeatherServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WeatherServiceImplPort, WeatherServiceImpl.class, features);
    }

}
