
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.king.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-02-05T16:27:26.763+05:30
 * Generated source version: 2.7.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "WeatherServiceImplService",
                      portName = "WeatherServiceImplPort",
                      targetNamespace = "http://service.king.com/",
                      wsdlLocation = "http://localhost:8077/7_ApacheCXF_Spring_integration/services/WeatherServiceImplPort?wsdl",
                      endpointInterface = "com.king.service.WeatherServiceImpl")
                      
public class WeatherServiceImplImpl implements WeatherServiceImpl {

    private static final Logger LOG = Logger.getLogger(WeatherServiceImplImpl.class.getName());

    /* (non-Javadoc)
     * @see com.king.service.WeatherServiceImpl#getWeatherByCityID(int  arg0 )*
     */
    public com.king.service.Weather getWeatherByCityID(int arg0) { 
        LOG.info("Executing operation getWeatherByCityID");
        System.out.println(arg0);
        try {
            com.king.service.Weather _return = new com.king.service.Weather();
            _return.setCityId(-1123008954);
            _return.setCityname("Cityname1383836174");
            _return.setTemparature(-1823564033);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.king.service.WeatherServiceImpl#getTempByWeather(com.king.service.Weather  arg0 )*
     */
    public int getTempByWeather(com.king.service.Weather arg0) { 
        LOG.info("Executing operation getTempByWeather");
        System.out.println(arg0);
        try {
            int _return = 848433035;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
