
package com.king.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-02-05T16:27:26.497+05:30
 * Generated source version: 2.7.8
 * 
 */
public final class WeatherServiceImpl_WeatherServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.king.com/", "WeatherServiceImplService");

    private WeatherServiceImpl_WeatherServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WeatherServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WeatherServiceImplService ss = new WeatherServiceImplService(wsdlURL, SERVICE_NAME);
        WeatherServiceImpl port = ss.getWeatherServiceImplPort();  
        
        {
        System.out.println("Invoking getWeatherByCityID...");
        int _getWeatherByCityID_arg0 = -746014034;
        com.king.service.Weather _getWeatherByCityID__return = port.getWeatherByCityID(_getWeatherByCityID_arg0);
        System.out.println("getWeatherByCityID.result=" + _getWeatherByCityID__return);


        }
        {
        System.out.println("Invoking getTempByWeather...");
        com.king.service.Weather _getTempByWeather_arg0 = new com.king.service.Weather();
        _getTempByWeather_arg0.setCityId(-1249492684);
        _getTempByWeather_arg0.setCityname("Cityname-1897382162");
        _getTempByWeather_arg0.setTemparature(184480478);
        int _getTempByWeather__return = port.getTempByWeather(_getTempByWeather_arg0);
        System.out.println("getTempByWeather.result=" + _getTempByWeather__return);


        }

        System.exit(0);
    }

}
