
package com.king.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-02-05T11:24:19.531+05:30
 * Generated source version: 2.7.8
 * 
 */
public final class CalService_CalServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.king.com/", "CalServiceService");

    private CalService_CalServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalServiceService ss = new CalServiceService(wsdlURL, SERVICE_NAME);
        CalService port = ss.getCalServicePort();  
        
        {
        System.out.println("Invoking add...");
        int _add_arg0 = 160265934;
        int _add_arg1 = -1285316986;
        int _add__return = port.add(_add_arg0, _add_arg1);
        System.out.println("add.result=" + _add__return);


        }

        System.exit(0);
    }

}
