package com.king.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-02-05T11:24:19.695+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.king.com/", name = "CalService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.king.com/", className = "com.king.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.king.com/", className = "com.king.service.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
