
package com.king;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalServiceImpl", targetNamespace = "http://www.king.com", wsdlLocation = "http://localhost:9999/02_JAX_WS_RI_CalService/calService?wsdl")
public class CalServiceImpl
    extends Service
{

    private final static URL CALSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException CALSERVICEIMPL_EXCEPTION;
    private final static QName CALSERVICEIMPL_QNAME = new QName("http://www.king.com", "CalServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/02_JAX_WS_RI_CalService/calService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALSERVICEIMPL_WSDL_LOCATION = url;
        CALSERVICEIMPL_EXCEPTION = e;
    }

    public CalServiceImpl() {
        super(__getWsdlLocation(), CALSERVICEIMPL_QNAME);
    }

    public CalServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALSERVICEIMPL_QNAME, features);
    }

    public CalServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, CALSERVICEIMPL_QNAME);
    }

    public CalServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALSERVICEIMPL_QNAME, features);
    }

    public CalServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalService
     */
    @WebEndpoint(name = "CalServiceImplPort")
    public CalService getCalServiceImplPort() {
        return super.getPort(new QName("http://www.king.com", "CalServiceImplPort"), CalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalService
     */
    @WebEndpoint(name = "CalServiceImplPort")
    public CalService getCalServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.king.com", "CalServiceImplPort"), CalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALSERVICEIMPL_EXCEPTION!= null) {
            throw CALSERVICEIMPL_EXCEPTION;
        }
        return CALSERVICEIMPL_WSDL_LOCATION;
    }

}
